/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.junit.test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testSum() {
        var expected = 5;
        var actual = App.sum(3, 2);
        assertEquals(expected, actual);
    }

}
