/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.junit.test;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static int sum(int a, int b) {
        return a + b;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}

